# Site settings
title: de Schildertuin
email: nogniet@...
description: > # this means to ignore newlines until "baseurl:"
   Dit is de placeholder beschrijving ;)
baseurl: "/wordpress" # the subpath of your site, e.g. /blog/
url: "http://www.schildertuin.nl" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 5

# Build settings
markdown: kramdown
